## Testing Storing NP Arrays in SQLite

In [1]:
import pickle
import pandas as pd
import numpy as np
from sql_scripts import create_connection, encode_array_for_sql, decode_array_from_sql

In [2]:
conn = create_connection("spectrograms.db")

2.6.0


In [3]:
t_t_v = ['train','test','train','val','val','test','test','val','train']
words = ['cat','one','left','up','car','seven','bird','hello','goodbye']

image = np.array(
[
    [0.,1.,2.,3.,4.],
    [0.,1.,2.,3.,4.],
    [0.,1.,2.,3.,4.],
    [0.,1.,2.,3.,4.],
])

x_sizes = []
y_sizes = []
images = []
for i in range(9):
    x_sizes.append(image.shape[1])
    y_sizes.append(image.shape[0])
    images.append(encode_array_for_sql(image))
type(images[0])

str

In [5]:
df = pd.DataFrame({'t_t_v':t_t_v,'words':words,'x_size':x_sizes,'y_size':y_sizes,'images':images})
df.to_sql('specgrams', conn, if_exists='replace', index=False)

verification_df = pd.read_sql('SELECT * FROM specgrams', conn)
verification_df

t_t_v    words  x_size  y_size  \
0  train      cat       5       4   
1   test      one       5       4   
2  train     left       5       4   
3    val       up       5       4   
4    val      car       5       4   
5   test    seven       5       4   
6   test     bird       5       4   
7    val    hello       5       4   
8  train  goodbye       5       4   

                                              images  
0  ð?@@@...  
1  ð?@@@...  
2  ð?@@@...  
3  ð?@@@...  
4  ð?@@@...  
5  ð?@@@...  
6  ð?@@@...  
7  ð?@@@...  
8  ð?@@@...

In [6]:
for index, row in verification_df.iterrows():
    print(decode_array_from_sql(row.images,row.x_size,row.y_size))

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
